# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET MAUI Android

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup .NET MAUI
        run: dotnet workload install maui
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey=format('Apple Distribution{0} John Smith (AY2GDE9QM7)', ':') -p:CodesignProvision="MyMauiApp"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          path: ./**/*.ipa
